---
apiVersion: v1
kind: Service
metadata:
  name: figalize
  namespace: default
spec:
  selector:
    app: figalize
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000