---
apiVersion: v1
kind: Service
metadata:
  name: figalize
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9090'
spec:
  selector:
    app: figalize
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000