
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  imagizer
  namespace: default
  labels:
    app:  imagizer
spec:
  selector:
    matchLabels:
      app: imagizer
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/metrics'
          prometheus.io/port: '80'
      labels:
        app:  imagizer
    spec:
      imagePullSecrets: 
      - name: registry-secret
      containers:
      - name:  imagizer
        image:  registry.gitlab.com/realscorp/figachechnaya/imagizer:1.0.1
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 800m
            memory: 600Mi
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: IMAGIZER_API_PORT
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: IMAGIZER_API_PORT
        - name: KAFKA_BOOTSTRAP
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: KAFKA_BOOTSTRAP
        - name: KAFKA_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: KAFKA_TOPIC_NAME
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: KAFKA_GROUP_ID
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: S3_BUCKET
        - name: S3_PATH
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: S3_PATH
        - name: S3_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: S3_ENDPOINT
        - name: S3_FONT_LINK
          valueFrom:
            configMapKeyRef:
              name: imagizer-env
              key: S3_FONT_LINK
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: imagizer
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: imagizer
              key: s3_secret_key
        ports:
        - containerPort: 80
          name:  api
      restartPolicy: Always
