---
apiVersion: v1
kind: Service
metadata:
  name: imagizer
  namespace: default
spec:
  selector:
    app: imagizer
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80