---
kind: ConfigMap
apiVersion: v1
metadata:
  name: figalize-files
  namespace: default
data:
  example.json: |
    {
        "schemas": [
            {
                "name": "Фигачечная",
                "substitutions": [
                    {
                        "keys": "ая",
                        "value": "Фига"
                    },
                    {
                        "keys": "о",
                        "value": "Фиго"
                    },
                    {
                        "keys": "эе", 
                        "value": "Фиге"
                    },
                    {
                        "keys": "ё", 
                        "value": "Фигё"
                    },
                    {
                        "keys": "ую",
                        "value": "Фигу"
                    },
                    {
                        "keys": "ыи",
                        "value": "Фиги"
                    }
                ]    
            },
            {
                "name": "Хреначечная",
                "substitutions": [
                    {
                        "keys": "ая",
                        "value": "Хрена"
                    },
                    {
                        "keys": "о",
                        "value": "Хрено"
                    },
                    {
                        "keys": "эеё", 
                        "value": "Хренё"
                    },
                    {
                        "keys": "ую",
                        "value": "Хрену"
                    },
                    {
                        "keys": "ыи",
                        "value": "Хрени"
                    }
                ]
            }
        ]
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: figalize-env
  namespace: default
data:
  HISTORY_APPEND_URL: http://history:8000/api/append/
  METRICS_PORT_FIGALIZE: '9090'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  figalize
  namespace: default
  labels:
    app:  figalize
spec:
  selector:
    matchLabels:
      app: figalize
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  figalize
    spec:
      containers:
      - name:  figalize
        image:  realscorp/figalize:0.3.1
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 400Mi
        readinessProbe:
          httpGet:
            path: /api/healthz/
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: METRICS_PORT_FIGALIZE
          valueFrom:
            configMapKeyRef:
              name: figalize-env
              key: METRICS_PORT_FIGALIZE
        - name: HISTORY_APPEND_URL
          valueFrom:
            configMapKeyRef:
              name: figalize-env
              key: HISTORY_APPEND_URL
        ports:
        - containerPort: 8000
          name:  api
        volumeMounts:
        - name: config-volume
          mountPath: /var/config/
      volumes:
        - name: config-volume
          configMap:
            name: figalize-files
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: figalize
  namespace: default
spec:
  selector:
    app: figalize
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000