.dockerbuild:
  extends: .init
  image: docker:22.06-rc-dind
  stage: build
  allow_failure: true # без этого пайплайн будет постоянно висеть в статусе blocked или running
  variables:
    WORKINGDIR_ROOT: ${CI_PROJECT_DIR}/$CODE_DIR
  script:
    - cd $WORKINGDIR_ROOT
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t=$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_TAG

validate/image/front:
  extends: .init
  stage: validate
  allow_failure: true # без этого пайплайн будет постоянно висеть в статусе blocked или running
  image: pipelinecomponents/hadolint:0.23.3
  variables:
    WORKINGDIR_ROOT: ${CI_PROJECT_DIR}/frontend
  script:
    - cd $WORKINGDIR_ROOT
    - hadolint Dockerfile

validate/image/figalize:
  extends: .init
  stage: validate
  allow_failure: true # без этого пайплайн будет постоянно висеть в статусе blocked или running
  image: pipelinecomponents/hadolint:0.23.3
  variables:
    WORKINGDIR_ROOT: ${CI_PROJECT_DIR}/microservices/figalize
  script:
    - cd $WORKINGDIR_ROOT
    - hadolint Dockerfile

validate/image/history:
  extends: .init
  stage: validate
  allow_failure: true # без этого пайплайн будет постоянно висеть в статусе blocked или running
  image: pipelinecomponents/hadolint:0.23.3
  variables:
    WORKINGDIR_ROOT: ${CI_PROJECT_DIR}/microservices/history
  script:
    - cd $WORKINGDIR_ROOT
    - hadolint Dockerfile

build/image/front:
  extends: .dockerbuild
  variables:
    IMAGE_TAG: front:1.0.0
    CODE_DIR: frontend
  rules:
    - if: '$CI_PIPELINE_SOURCE != "web"' # Если пайп запущен не вручную через веб-фейс
      changes: # и в коммите были изменены файлы в каталоге сервиса, запускаем джобу автоматически
        - $CODE_DIR/**/*
      when: always
    - exists: # В противном случае - запускаем вручную
        - $CODE_DIR/**/*
      when: manual
  needs:
    - job: validate/image/front

build/image/figalize:
  extends: .dockerbuild
  variables:
    IMAGE_TAG: figalize:1.0.0
    CODE_DIR: microservices/figalize
  rules:
    - if: '$CI_PIPELINE_SOURCE != "web"' # Если пайп запущен не вручную через веб-фейс
      changes: # и в коммите были изменены файлы в каталоге сервиса, запускаем джобу автоматически
        - $CODE_DIR/**/*
      when: always
    - exists: # В противном случае - запускаем вручную
        - $CODE_DIR/**/*
      when: manual
  needs:
    - job: validate/image/figalize

build/image/history:
  extends: .dockerbuild
  variables:
    IMAGE_TAG: history:1.0.0
    CODE_DIR: microservices/history
  rules:
    - if: '$CI_PIPELINE_SOURCE != "web"' # Если пайп запущен не вручную через веб-фейс
      changes: # и в коммите были изменены файлы в каталоге сервиса, запускаем джобу автоматически
        - $CODE_DIR/**/*
      when: always
    - exists: # В противном случае - запускаем вручную
        - $CODE_DIR/**/*
      when: manual
  needs:
    - job: validate/image/history
