stages:
  - validate
  - build
  - deploy

.init:
  before_script:
    - echo -e "\e[47m\e[0Ksection_start:`date +%s`:env_vars[collapsed=true]\r\e[0KList env vars" # Красивые сворачивающиеся разделы в логе джоба
    - cd $WORKINGDIR_ROOT
    - env | sort -f # выводим все немаскированные переменные окружения с целью упрощения отладки. список сортируем
    - echo -e "\e[0Ksection_end:`date +%s`:env_vars\r\e[0K" # Сворачиваем секцию лога

.dockerbuild:
  extends: .init
  image: docker:22.06-rc-dind
  stage: build
  allow_failure: true # без этого пайплайн будет постоянно висеть в статусе blocked или running
  variables:
    WORKINGDIR_ROOT: ${CI_PROJECT_DIR}/$CODE_DIR
  script:
    - cd $WORKINGDIR_ROOT
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t=$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_TAG